version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/strands-mcp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci(mcp)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
